### ISSUE TITLE
[macOS] "Unsigned application allowed" rollback fails

### ISSUE THREAD

**Issue by quentinvedrenne** [edamametechnologies/threatmodels#25]
Tested on MacOS Ventura (with Helper installed), virtual machine, applying rollback to “Unsigned application allowed” throws an error.

**Comment by mkuhn19** [comment]
rollback is working, spctl is correctly disabled. The implementation (used to check the threat) seems to be the problem as it returns a -1 error code

**Comment by mkuhn19** [comment]
implementation target is fine. It is working on a local project using run_script crate (same version as edamame)
