### ISSUE TITLE
"file sharing enabled" rollback action doesn't fully activate file sharing

### ISSUE THREAD

**Issue by franklyonnet** [edamametechnologies/threatmodels#3]
launchctl load -w /System/Library/LaunchDaemons/com.apple.smbd.plist; defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server.plist EnabledServices -array disk

required an additional step of enabling users for smbd (available through UI) - need an equivalent for CLI.

**Comment by franklyonnet** [comment]
Additionally, this rollback depends on "local firewall disabled" rollback action.

**Comment by quentinvedrenne** [comment]
done
