### ISSUE TITLE
Implement a metric to disable the SMBv1 protocol

### ISSUE THREAD

**Issue by andrewmhdb** [edamametechnologies/threatmodels#36]
This protocol is outdated and has known vulnerabilities that can allow attackers to take over your system. It should be disabled to improve the system's security.

**Comment by andrewmhdb** [comment]
The base implementation have been done in branch 36-metric-disable-smbv1. However the remediation and rollback are not working: they are running infinitly in the Edamame app and in GitHub actions CI/CD.

**Comment by PierreLamusse** [comment]
Capture/remediation/rollback are working, but a computer restart is needed in order to activate the changes. We need to find a way to handle this case by finding a proper UX flow.
