### ISSUE TITLE
"unprotected system wide changes" remediation fails

### ISSUE THREAD

**Issue by franklyonnet** [edamametechnologies/threatmodels#7]
security authorizationdb read system.preferences > /tmp/system.preferences.plist; defaults write /tmp/system.preferences.plist shared -bool false; security authorizationdb write system.preferences < /tmp/system.preferences.plist 
is not delivering the expected result

**Comment by edamametechnologies** [comment]
Fixed using NIST's version:  security authorizationdb read system.preferences > /tmp/system.preferences.plist; /usr/libexec/PlistBuddy -c \"Set :shared true\" /tmp/system.preferences.plist; security authorizationdb write system.preferences < /tmp/system.preferences.plist
